apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
